services:
  postgres:
    image: postgres:15
    container_name: postgres-db-doan-python
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: myapp
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_python:/var/lib/postgresql/data

volumes:
  postgres_data_python: